apiVersion: hub.traefik.io/v1alpha1
kind: APIAuth
metadata:
  name: default-auth
  namespace: apps
spec:
  isDefault: true
  jwt:
     appIdClaim: client_id
     jwksUrl: ${INTERNAL_OIDC_ISSUER}/protocol/openid-connect/certs
---
apiVersion: hub.traefik.io/v1alpha1
kind: API
metadata:
  name: weather-api
  namespace: apps
spec:
  openApiSpec:
    path: /openapi.yaml
    override:
      servers:
        - url: "${API_SERVER_URL}"
  cors:
    allowHeadersList:
      - "*"
    allowOriginsList:
      - "*"
    allowMethodsList:
      - "*"
    exposeHeadersList:
      - "*"
    addVaryHeader: true
    allowCredentials: true
    allowOriginListRegex:
      - ".*"
    maxAge: 86400
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: weather-ingress
  namespace: apps
  annotations:
    hub.traefik.io/api: weather-api@apps
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/weather`)
      kind: Rule
      services:
        - name: weather-app
          port: 3000

