apiVersion: hub.traefik.io/v1alpha1
kind: APIPlan
metadata:
  name: standard-plan
  namespace: apps
spec:
  title: Standard Plan
  description: Standard access to APIs
  rateLimit:
    limit: 100
    period: 1s
  quota:
    limit: 1000
    period: 1h

---
apiVersion: hub.traefik.io/v1alpha1
kind: APICatalogItem
metadata:
  name: standard-plan
  namespace: apps
spec:
  everyone: true
  apis:
    - name: weather-api
  apiPlan:
    name: standard-plan

---

apiVersion: hub.traefik.io/v1alpha1
kind: ManagedApplication
metadata:
  name: partner-app-jwt
  namespace: apps
spec:
  appId: traefik
  owner: "67f67907ee260b44336a952e"

---
apiVersion: hub.traefik.io/v1alpha1
kind: ManagedSubscription
metadata:
  name: partner-subscription
  namespace: apps
spec:
  managedApplications:
    - name: partner-app-jwt
  apis:
    - name: weather-api
  apiPlan:
    name: standard-plan